sequenceDiagram
    participant browser
    participant server
    
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    Note right of browser: POST request contains new note as JSON data containing both the content and the timestamp
    server-->>browser: HTML status code 201 (new note created)
    deactivate server
